export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const FETCH_USER = 'FETCH_USER';

export const MESSAGE_DELETED = 'MESSAGE_DELETED';
